config/routes.rb
Uasco::Application.routes.draw do

  get 'me' => 'pages#me', as: 'me'
  post 'me' => 'pages#update_me'
  get 'test' => 'pages#test'
  devise_for :users
  resources :users
  resources :clients do
    collection do
      get 'compare'
    end
    member do
      get 'attachments'
      post 'attachments' => 'clients#add_attachment'
      post 'attachments/:aid' => 'clients#set_default_attachment'
      delete 'attachments/:aid' => 'clients#delete_attachment'
      get 'sensors' => 'clients#get_sensors'
      post 'sensors' => 'clients#update_sensors'
      get 'check_new'
      get 'import_usb'
      post 'import_usb' => 'clients#import_usb_post'
      get 'export'
      get 'standard_export'
      get 'import'
      post 'import' => 'clients#import_data'
      get 'live'
      get 'archive_data'
      get 'export'
      get 'export_standard'
      get 'export_shown_data'
      get 'export_live_data'
    end
  end
  resources :sensors
  resources :client_infos

  post "post_data" => "packet#recieve"

  get 'RDLSystemServer/update.php' => 'pages#get_update'

  post "/RDLSystemServer/server.php" => "packet#recieve"
  get "/RDLSystemServer/server.php" => "packet#recieve"

  post "/RDLSecondServer/server.php" => "packet#second_recieve", as: :second_server_post
  get "/RDLSecondServer/server.php" => "packet#second_recieve"

  root 'pages#app'
  get 'about' => 'pages#about'
  get 'gallery' => 'pages#gallery'
  get 'products' => 'pages#products'
  get 'contact' => 'pages#contact'

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_client, only: [:show, :edit, :update, :destroy, :archive_data]
  before_action {@app = true}
  before_action {@tab = 'client'}

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  def check_new
    @sensor = @client.sensors.where(channel_index: params[:channel]).first if params[:channel]
    values = []
    if not params[:last].blank? and @sensor
      last = Time.at(params[:last].to_i+1)
      values = @client.values.where(channel_index: @sensor.channel_index).where('sample_time > ?', last)
    end
    # if values.count > 0
    #   values.each do |t|
    #     puts ">> #{t.sample_time-t.sample_time.utc_offset}"
    #   end
    # end
    if values.count > 0
      last = values.collect(&:sample_time).max.to_i
      values = values.sort_by(&:sample_time).reverse
      render json: {last: values.first.sample_time.to_i, values: values.map{|v| [v.sample_time.to_i, v.value.round_n] }}
    else
      render json: {values: []}
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @first_value = @client.values.where(channel_index: @client.sensors.pluck(:channel_index)).first
  end

  def archive_data
    if params.has_key?(:range)
      @range = params[:range].to_i
    else
      @range = 3
    end
    range_selector = @range == 0 ? @client.sampling_time : UConf[:range_selector][@range]
    range_selector = @client.sampling_time if not range_selector or range_selector < @client.sampling_time
    range_selector = range_selector.to_i
    @average = params[:average].to_i
    @sensors = @client.sensors.where(channel_index: params[:channel]).sort_by(&:channel_index).to_a
    gsensors = @sensors.group_by(&:channel_index)

    @first_value = @client.values.where(channel_index: @client.sensors.pluck(:channel_index)).first
    
    begin
      @from = JalaliDate.new( *(params[:from].split('/').collect(&:to_i))) if params[:from]
      @to = JalaliDate.new( *(params[:to].split('/').collect(&:to_i))) if params[:to]
    rescue ArgumentError
    end


    return if not @from or not @to
    # return flash.now[:error] = "ابتدای بازه انتخاب نشده است." unless @from
    # return flash.now[:error] = "انتهای بازه انتخاب نشده است." unless @to

    
    from_g = @from.to_g.to_datetime.in_time_zone("Tehran").at_beginning_of_day
    to_g = @to.to_g.to_datetime.in_time_zone("Tehran").at_end_of_day
    # my_logger.info "#{from_g}     #{to_g}"
    first_value = @client.values.where(channel_index: gsensors.keys, sample_time: from_g..to_g).first
    last_value = @client.values.where(channel_index: gsensors.keys, sample_time: from_g..to_g).last
    
    return flash.now[:error] = "بازه انتخاب شده اشتباه می باشد." unless from_g <= to_g
    return flash.now[:error] = "هیچ داده‌ای در این بازه وجود ندارد" unless first_value
    
    if to_g > first_value.sample_time
      to_g = first_value.sample_time
      @to = JalaliDate.new to_g
    end
    if from_g < last_value.sample_time
      from_g = last_value.sample_time
      @from = JalaliDate.new from_g
    end

    limit = 5000
    if (to_g.to_i - from_g.to_i) / range_selector > limit
      from_g = to_g - (limit*range_selector).seconds
      @from = JalaliDate.new from_g
      flash.now[:error] = "داده‌های دوره‌ی درخواست شده غیر قابل پردازش است." 
    end

    if params[:channel] and params[:channel].is_a? Array
      @chartLabels = ['تاریخ']
      @sensors.each{|s| @chartLabels << s.name+" ("+s.measure_unit+")"}
      # Rails.logger.info ">>>#{@chartLabels}"
      @from_g = from_g
      @to_g = to_g
      @range_selector = range_selector
      @chartData = @client.show(from_g, to_g, @sensors, range_selector, @average)
      # Rails.logger.info ">>>>#{@chartData}"
      if @client.values.first
        @last_value = @client.values.first.sample_time.to_i
      else
        @last_value = 0
      end
    end
  rescue ArgumentError
  #   return redirect_to client_path(@client)
  end

  def compare
    if params.has_key?(:range)
      @range = params[:range].to_i
    else
      @range = 3
    end
    @tab = 'compare'
    @clients = Client.includes(:sensors).all.to_a
    @average = params[:average].to_i
    @sensor1 = nil
    @sensor2 = nil
    
    if params[:channel2] and params[:channel1]
      channel1 = params[:channel1].split(",")
      @client1 = @clients.find{|c| c.id == channel1[0].to_i}
      return unless @client1
      @sensor1 = @client1.sensors.where(channel_index: channel1[1]).first
      return unless @sensor1
      channel2 = params[:channel2].split(",")
      @client2 = @clients.find{|c| c.id == channel2[0].to_i}
      return unless @client2
      @sensor2 = @client2.sensors.where(channel_index: channel2[1]).first
      return unless @sensor2
    end
    
    begin
      @from = JalaliDate.new( *(params[:from].split('/').collect(&:to_i))) if params[:from]
      @to = JalaliDate.new( *(params[:to].split('/').collect(&:to_i))) if params[:to]
    rescue ArgumentError
    end
    
    if @sensor1 and @sensor2 and @from and @to
      @range = params[:range].to_i
      min_range = [@client1.sampling_time, @client2.sampling_time].min
      range_selector = @range == 0 ? min_range : UConf[:range_selector][@range]
      range_selector = min_range if not range_selector or range_selector < min_range
      from_g = @from.to_g.to_datetime.in_time_zone("Tehran").at_beginning_of_day
      to_g = @to.to_g.to_datetime.in_time_zone("Tehran").at_end_of_day
      first_value1 = @client1.values.where(channel_index: @sensor1.channel_index, sample_time: from_g..to_g).first
      last_value1 = @client1.values.where(channel_index: @sensor1.channel_index, sample_time: from_g..to_g).last
      first_value2 = @client2.values.where(channel_index: @sensor2.channel_index, sample_time: from_g..to_g).first
      last_value2 = @client2.values.where(channel_index: @sensor2.channel_index, sample_time: from_g..to_g).last

      return flash.now[:error] = "بازه انتخاب شده اشتباه می باشد." unless from_g <= to_g
      return flash.now[:error] = "هیچ داده‌ای در این بازه وجود ندارد." if first_value1.nil? and first_value2.nil?
      
      if first_value1.nil?
        first_value = first_value2.sample_time
        last_value = last_value2.sample_time
      elsif first_value2.nil?
        first_value = first_value1.sample_time
        last_value = last_value1.sample_time
      else
        first_value = [first_value1.sample_time, first_value2.sample_time].max
        last_value = [last_value1.sample_time, last_value2.sample_time].min
      end

      if to_g > first_value
        to_g = first_value
        @to = JalaliDate.new to_g
      end
      if from_g < last_value
        from_g = last_value
        @from = JalaliDate.new from_g
      end
      limit = 5000
      if (to_g.to_i - from_g.to_i) / range_selector > limit
        from_g = to_g - (limit*range_selector).seconds
        @from = JalaliDate.new from_g
        flash.now[:error] = "داده‌های دوره‌ی درخواست شده غیر قابل پردازش است." 
      end

      @chartLabels = ['تاریخ', "#{@client1.name} - #{@sensor1.name}(#{@sensor1.measure_unit})", "#{@client2.name} - #{@sensor2.name}(#{@sensor2.measure_unit})"]
      @chartData = @client1.compare(from_g, to_g, range_selector, @average, @client1.id, @sensor1.channel_index, @client2.id, @sensor2.channel_index)

    end
  rescue ArgumentErrore
    # return redirect_to client_path(@client)
  end

  def live
    @sensor = @client.sensors.where(channel_index: params[:channel]).first if params[:channel]
    if @sensor
      values = @client.values.where(channel_index: @sensor.channel_index).limit(100).reverse
      @first_value = values.last
      
      @from = values.first.sample_time.to_datetime.in_time_zone("Tehran")
      
      @chartData = "["
      values.each do |v|
        # t = v.sample_time
        # @chartData += "[new Date(#{t.year},#{t.month-1},#{t.day},#{t.hour},#{t.min},#{t.sec}),#{v.value}],"
        @chartData += "[new Date(\"#{v.sample_time.to_datetime.strftime}\"),#{v.value.round_n}],"
      end
      @chartData = @chartData[0..-2]+"]"
      if @first_value
        @last_value = @first_value.sample_time.to_i
      else
        @last_value = 0
      end
      @chartLabels = ['تاریخ', @sensor.name+"("+@sensor.measure_unit+")"]
    end
  end

  def get_sensors
    @sensors = @client.sensors
  end

  def update_sensors
    if params[:sensors] and params[:sensors].is_a? Array
      @client.update_attributes sensor_ids: params[:sensors]
    end
    @sensors = @client.sensors
    render 'get_sensors'
  end

  def attachments
    @attachments = @client.attachments
  end

  def add_attachment
    if params[:files]
      puts ">> #{params[:files]}"
      if params[:files].is_a? Array
        params[:files].each do |file|
          @client.attachments.create file: file
        end
      else
        @client.attachments.create file: params[:files]
      end
    end
    redirect_to attachments_client_path(@client)
  end

  def set_default_attachment
    @client.update_attributes default_attachment: params[:aid]
    redirect_to attachments_client_path(@client)
  end

  def delete_attachment
    @client.attachments.find(params[:aid]).destroy
    redirect_to attachments_client_path(@client)
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    if @client.save
      if params[:zipupdate] or params[:static_ip]
        _params = {}
        _params[:static_ip] = params[:static_ip] if params[:static_ip]
        _params[:zipupdate] = params[:zipupdate] if params[:zipupdate]
        @client.client_info.update _params
      end
      redirect_to @client
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/archive_data.html.erb
<%= link_to "بازگشت", client_path(@client) %>
<h2><%= @client.client_info ? @client.client_info.name : "#{t 'without'} #{t 'client_info'}" %></h2>
<h3>آرشیو داده ها</h3>
<br>
<div class="row">
  <div class="col-sm-6">
    <h4>اطلاعات <%= t 'client' %></h4>
    <dl class="dl-horizontal">
      <dt><%= t 'description' %></dt>
      <dd><%= @client.client_info ? @client.client_info.description : '' %></dd>
      <dt><%= raw(t('sampling_time')) %></dt>
      <dd><%= @client.sampling_time %></dd>
      <dt><%= raw(t('samples_count')) %></dt>
      <dd><%= @client.sampling_time * @client.samples_count %></dd>
      <dt><%= t 'model' %></dt>
      <dd><%= @client.client_info ? @client.client_info.model_name : '' %></dd>
      <dt><%= t 'serial' %></dt>
      <dd><%= @client.client_info ? @client.client_info.serial_number : '' %></dd>
      <dt><%= t 'last_data' %></dt>
      <dd><%= @first_value ? persian_date(@first_value.sample_time) : 'بدون داده' %></dd>
    </dl>
    <br>
    <br>
  </div>
  <div class="col-sm-6">
    <% attachments = @client.attachments %>
    <p class="lead"></p>
    <%= link_to "گالری عکسها", attachments_client_path(@client) %>
    <% if attachments.count > 0 %>
      <div class="clearfix rslides_container">
        <ul class="rslides" id="slider">
          <% attachments.each do |attachment| %>
            <li>
              <%= link_to attachment.file.url(:original), target: '_blank' do %>
                <%= image_tag attachment.file.url %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <p class="lead"></p>
    <% end %>
  </div>
  <div class="col-sm-12">
    <form action="<%= archive_data_client_path(@client) %>" method="get" class="row clearfix">
      <div class="col-sm-6">
        <div class="form-group fcheckbox">
          <% @client.sensors.sort_by(&:channel_index).each do |sensor| %>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="channel[]" value="<%= sensor.channel_index %>" <%= "checked" if @sensors.include? sensor %>> <%= sensor.name %>
              </label>
            </div>
          <% end %>
        </div>

        <button type="submit" class="btn btn-default">نمایش</button>
      </div>

      <div class="form-horizontal col-sm-6">
        <div class="form-group">
          <label for="from" class="col-sm-2">از: </label>
          <div class="col-sm-8">
            <input type="text" class="form-control pcal" id="from" name="from" <%= "value=#{@from.to_s}" if @from %>>
          </div>
        </div>

        <div class="form-group">
          <label for="to" class="col-sm-2">تا: </label>
          <div class="col-sm-8">
            <input type="text" class="form-control pcal" id="to" name="to" <%= "value=#{@to.to_s}" if @to %>>
          </div>
        </div>

        <div class="form-group">
          <label for="range" class="col-sm-2">بازه: </label>
          <div class="col-sm-8">
            <%= select_tag :range, options_for_select(range_options, @range), class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="average" class="col-sm-2">نوع محاسبه: </label>
          <div class="col-sm-8">
            <%= select_tag :average, options_for_select(average_options, @average), class: "form-control" %>
          </div>
        </div>

      </div>
    </form>

    <% if @chartData %>
      <hr>
      <div class="chart" style="width:800px;padding-right:50px"></div>
      <p class="lead"></p>
      <div class="table-wrapper">
        <table class="table table-bordered" style="direction:ltr;">
          <thead>
            <tr class="chartHead"></tr>
          </thead>
          <tbody class="chartTable"></tbody>
        </table>
      </div>
      <p class="lead"></p>
      <div class="center-block" style="width:200px;">
        <%= link_to t('export_shown_data'), export_shown_data_client_path(@client, from: @from, to: @to, channel: @sensors.collect(&:channel_index), range_selector: @range_selector, average: @average), class: 'btn btn-primary btn-block', target: "_blank" %>
      </div>
      <script>
        window.chart = <%= raw @chartData %>;
        window.chartLabels = <%= raw @chartLabels.to_json %>;
        window.sampleTime = <%= @client.sampling_time*@client.samples_count %>;
      </script>
    <% end %>
  </div>
</div>

app/views/clients/export.html.erb
<%= link_to "بازگشت", client_path(@client) %>
<h2><%= @client.client_info ? @client.client_info.name : "#{t 'without'} #{t 'client_info'}" %></h2>
<h3>اکسپورت</h3>
<div class="row">
  <div class="col-sm-6">
    <h4>اطلاعات <%= t 'client' %></h4>
    <dl class="dl-horizontal">
      <dt><%= t 'description' %></dt>
      <dd><%= @client.client_info ? @client.client_info.description : '' %></dd>
      <dt><%= raw(t('sampling_time')) %></dt>
      <dd><%= @client.sampling_time %></dd>
      <dt><%= raw(t('samples_count')) %></dt>
      <dd><%= @client.sampling_time * @client.samples_count %></dd>
      <dt><%= t 'model' %></dt>
      <dd><%= @client.client_info ? @client.client_info.model_name : '' %></dd>
      <dt><%= t 'serial' %></dt>
      <dd><%= @client.client_info ? @client.client_info.serial_number : '' %></dd>
      <dt><%= t 'last_data' %></dt>
      <dd><%= @first_value ? persian_date(@first_value.sample_time) : 'بدون داده' %></dd>
    </dl>
  </div>
  <br>
  <br>
  <div class="col-sm-6">
    <% attachments = @client.attachments %>
    <p class="lead"></p>
    <%= link_to "گالری عکسها", attachments_client_path(@client) %>
    <% if attachments.count > 0 %>
      <div class="clearfix rslides_container">
        <ul class="rslides" id="slider">
          <% attachments.each do |attachment| %>
            <li>
              <%= link_to attachment.file.url(:original), target: '_blank' do %>
                <%= image_tag attachment.file.url %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <p class="lead"></p>
    <% end %>
  </div>
  <div class="col-sm-12">
    <form action="<%= export_client_path(@client) %>" method="get" class="row clearfix">
      <div class="col-sm-6">
        <div class="form-group fcheckbox">
          <% @client.sensors.sort_by(&:channel_index).each do |sensor| %>
            <div class="checkbox">
              <label>
                <input type="checkbox" name="channel[]" value="<%= sensor.channel_index %>" <%= "checked" if @sensors.include? sensor %>> <%= sensor.name %>
              </label>
            </div>
          <% end %>
        </div>

        <button type="submit" class="btn btn-default">دریافت</button>
      </div>

      <div class="form-horizontal col-sm-6">
        <div class="form-group">
          <label for="from" class="col-sm-2">از: </label>
          <div class="col-sm-8">
            <input type="text" class="form-control pcal" id="from" name="from" <%= "value=#{@from.to_s}" if @from %>>
          </div>
        </div>

        <div class="form-group">
          <label for="to" class="col-sm-2">تا: </label>
          <div class="col-sm-8">
            <input type="text" class="form-control pcal" id="to" name="to" <%= "value=#{@to.to_s}" if @to %>>
          </div>
        </div>

      </div>
    </form>
  </div>
</div>

app/views/clients/get_sensors.html.erb
<h4>انتخاب <%= t 'sensors' %>ی موجود در <%= link_to @client.client_info ? @client.client_info.name : t('client'), @client %></h4>
<%= link_to "بازگشت", edit_client_path(@client) %>
<%= form_tag sensors_client_path(@client), class: 'form-horizontal' do %>
  <% Sensor.all.each do |sensor| %>
    <div class="checkbox">
      <label>
        <input type="checkbox" name="sensors[]" value="<%= sensor.id %>" <%= "checked" if @sensors.include? sensor %>> <%= sensor.name %>
      </label>
    </div>
  <% end %>
  <button type="submit" class="btn btn-default"><%= t 'submit' %></button>
<% end %>

app/views/clients/import.html.erb
<%= link_to "بازگشت", client_path(@client) %>
<h2><%= @client.client_info ? @client.client_info.name : "#{t 'without'} #{t 'client_info'}" %></h2>
<h3>ایمپورت داده</h3>
<div class="row">

  <div class="col-sm-6">
    <p class="lead"></p>
    <h4>اطلاعات <%= t 'client' %></h4>
    <dl class="dl-horizontal">
      <dt><%= t 'description' %></dt>
      <dd><%= @client.client_info ? @client.client_info.description : '' %></dd>
      <dt><%= raw(t('sampling_time')) %></dt>
      <dd><%= @client.sampling_time %></dd>
      <dt><%= raw(t('samples_count')) %></dt>
      <dd><%= @client.sampling_time * @client.samples_count %></dd>
      <dt><%= t 'model' %></dt>
      <dd><%= @client.client_info ? @client.client_info.model_name : '' %></dd>
      <dt><%= t 'serial' %></dt>
      <dd><%= @client.client_info ? @client.client_info.serial_number : '' %></dd>
    </dl>
  </div>

  <div class="col-sm-12">
  <br><br>
  <%= form_tag import_client_path(@client), method: :post, multipart: true do %>
    <div class="form-group">
      <label for="files">فایل اطلاعات :</label>
      <%= file_field_tag "file", type: :file %>
    </div>
    <button type="submit" class="btn btn-primary"><%= t 'submit' %></button>
  <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<h3><%= t 'list' %> <%= t 'clients' %></h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th class="text-center"><%= t 'tier' %></th>
      <th class="text-center"><%= t 'name' %></th>
      <th class="text-center"><%= t 'position' %></th>
      <th class="text-center"><%= t 'description' %></th>
      <% if can? :manage, Client %>
        <th class="text-center"><%= t 'settings' %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% counter = 0 %>
    <% @clients.each do |client| %>
      <tr class="text-center">
        <td><%= persian_numbers counter += 1 %></td>
        <td><%= link_to (client.client_info ? client.client_info.name : "#{t 'without'} #{t 'client_info'}"), client %></td>
        <td><%= client.client_info ? client.client_info.position : '' %></td>
        <td><%= client.client_info ? client.client_info.description : '' %></td>
        <% if can? :edit, client %>
          <td>
            <%= link_to t('edit'), edit_client_path(client) %>
            <%= link_to t('delete'), client, method: :delete, class: 'text-danger', data: { confirm: t('you_sure') } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Client %>
  <%= link_to icon('plus-circle', "افزودن #{t 'client'} جدید"), new_client_path, class: 'btn btn-primary' %>
<% end %>

app/views/clients/live.html.erb
<%= link_to "بازگشت", client_path(@client) %>
<h2><%= @client.client_info ? @client.client_info.name : "#{t 'without'} #{t 'client_info'}" %></h2>
<h3>نمایش آنلاین</h3>
<br>
<div class="row">
  <div class="col-sm-6">
    <p class="lead"></p>
    <h4>اطلاعات <%= t 'client' %></h4>
    <dl class="dl-horizontal">
      <dt><%= t 'description' %></dt>
      <dd><%= @client.client_info ? @client.client_info.description : '' %></dd>
      <dt><%= raw(t('sampling_time')) %></dt>
      <dd><%= @client.sampling_time %></dd>
      <dt><%= raw(t('samples_count')) %></dt>
      <dd><%= @client.sampling_time * @client.samples_count %></dd>
      <dt><%= t 'model' %></dt>
      <dd><%= @client.client_info ? @client.client_info.model_name : '' %></dd>
      <dt><%= t 'serial' %></dt>
      <dd><%= @client.client_info ? @client.client_info.serial_number : '' %></dd>
    </dl>
  </div>
  <div class="col-sm-6">
    <p class="lead"></p>
    <p>
      <%= t 'last_data' %><br>
      <strong class="last-value"><%= @first_value ? persian_date(@first_value.sample_time) : 'بدون داده' %></strong>
    </p>
    <p class="last-update">
      آخرین بروزرسانی مجدد :<br>
      <strong>بارگزاری اولیه</strong>
    </p>
    </dl>
  </div>
  <div class="col-sm-12">
    <form method="get" class="row clearfix">
      <div class="col-sm-6">
        <div class="form-group">
          <%= select_tag :channel, options_from_collection_for_select(@client.sensors.sort_by(&:channel_index), :channel_index, :name, @sensor ? @sensor.channel_index : ''), class: 'form-control' %>
        </div>

        <button type="submit" class="btn btn-default">نمایش</button>
      </div>
    </form>
    <% if @chartData %>
      <hr>
      <div class="chart" style="width:700px;padding-right:200px"></div>
      <p class="lead"></p>
      <div class="table-wrapper">
        <table class="table table-bordered" style="direction:ltr;">
          <thead>
            <tr class="chartHead"></tr>
          </thead>
          <tbody class="chartTable"></tbody>
        </table>
      </div>
      <p class="lead"></p>
      <div class="center-block" style="width:200px;">
        <%= link_to t('export_live_data'), export_live_data_client_path(@client, from: @from, sensor: @sensor.channel_index), class: 'btn btn-primary btn-block', target: "_blank" %>
      </div>
      <script>
        window.chart = <%= raw @chartData %>;
        window.chartLabels = <%= raw @chartLabels.to_json %>;
        window.lastValue = <%= @last_value %>;
        window.sampleTime = <%= @client.sampling_time*@client.samples_count %>;
        window.refreshUrl = "<%= check_new_client_path(@client) %>";
        window.channel = <%= @sensor.channel_index %>;
      </script>
    <% end %>
  </div>
</div>

app/views/clients/show.html.erb
<h2><%= @client.client_info ? @client.client_info.name : "#{t 'without'} #{t 'client_info'}" %></h2>
  <div class="row">
    <div class="col-sm-6">
      <%= link_to "بازگشت", clients_path %>
      <h4>اطلاعات <%= t 'client' %></h4>
      <dl class="dl-horizontal">
        <dt><%= t 'description' %></dt>
        <dd><%= @client.client_info ? @client.client_info.description : '' %></dd>
        <dt><%= raw(t('sampling_time')) %></dt>
        <dd><%= @client.sampling_time %></dd>
        <dt><%= raw(t('samples_count')) %></dt>
        <dd><%= @client.sampling_time * @client.samples_count %></dd>
        <dt><%= t 'model' %></dt>
        <dd><%= @client.client_info ? @client.client_info.model_name : '' %></dd>
        <dt><%= t 'serial' %></dt>
        <dd><%= @client.client_info ? @client.client_info.serial_number : '' %></dd>
        <dt><%= t 'last_data' %></dt>
        <dd><%= @first_value ? persian_date(@first_value.sample_time) : 'بدون داده' %></dd>
      </dl>
      <br>
      <br>
      <%= link_to t('archive_data'), archive_data_client_path(@client), class: 'btn btn-link' %><br>
      <%= link_to t('live'), live_client_path(@client), class: 'btn btn-link' %><br>
      <%= link_to t('export'), export_client_path(@client), class: 'btn btn-link' %><br>
      <%= link_to t('export_standard'), export_standard_client_path(@client), class: 'btn btn-link' %><br>
      <% if can? :update, @client %>
        <%= link_to t('import'), import_client_path(@client), class: 'btn btn-link' %><br>
        <%= link_to t('import_usb'), import_usb_client_path(@client), class: 'btn btn-link' %><br>
      <% end %>
    </div>
    <div class="col-sm-6">
      <% attachments = @client.attachments %>
      <p class="lead"></p>
      <%= link_to "گالری عکسها", attachments_client_path(@client) %>
      <% if attachments.count > 0 %>
        <div class="clearfix rslides_container">
          <ul class="rslides" id="slider">
            <% attachments.each do |attachment| %>
              <li>
                <%= link_to attachment.file.url(:original), target: '_blank' do %>
                  <%= image_tag attachment.file.url %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <p class="lead"></p>
      <% end %>
    </div>
  </div>