config/routes.rb
Uasco::Application.routes.draw do

  get 'me' => 'pages#me', as: 'me'
  post 'me' => 'pages#update_me'
  get 'test' => 'pages#test'
  devise_for :users
  resources :users
  resources :clients do
    collection do
      get 'compare'
    end
    member do
      get 'attachments'
      post 'attachments' => 'clients#add_attachment'
      post 'attachments/:aid' => 'clients#set_default_attachment'
      delete 'attachments/:aid' => 'clients#delete_attachment'
      get 'sensors' => 'clients#get_sensors'
      post 'sensors' => 'clients#update_sensors'
      get 'check_new'
      get 'import_usb'
      post 'import_usb' => 'clients#import_usb_post'
      get 'export'
      get 'standard_export'
      get 'import'
      post 'import' => 'clients#import_data'
      get 'live'
      get 'archive_data'
      get 'export'
      get 'export_standard'
      get 'export_shown_data'
      get 'export_live_data'
    end
  end
  resources :sensors
  resources :client_infos

  post "post_data" => "packet#recieve"

  get 'RDLSystemServer/update.php' => 'pages#get_update'

  post "/RDLSystemServer/server.php" => "packet#recieve"
  get "/RDLSystemServer/server.php" => "packet#recieve"

  post "/RDLSecondServer/server.php" => "packet#second_recieve", as: :second_server_post
  get "/RDLSecondServer/server.php" => "packet#second_recieve"

  root 'pages#app'
  get 'about' => 'pages#about'
  get 'gallery' => 'pages#gallery'
  get 'products' => 'pages#products'
  get 'contact' => 'pages#contact'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  has_many :client_sensors
  has_many :sensors, through: :client_sensors

  validates_presence_of :name, message: "#{I18n.t 'name'} نمیتواند خالی باشد"
  validates_presence_of :channel_index, message: "#{I18n.t 'channel_index'} نمیتواند خالی باشد"
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]
  before_action {@app = true}
  before_action {@tab = 'sensor'}

  def index
    @sensors = Sensor.all
  end

  def show
  end

  def new
    @sensor = Sensor.new
  end

  def edit
  end

  def create
    @sensor = Sensor.new(sensor_params)

    if @sensor.save
      redirect_to @sensor, notice: 'Sensor was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @sensor.update(sensor_params)
      redirect_to @sensor, notice: 'Sensor was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @sensor.destroy
    redirect_to sensors_url
  end

  private
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    def sensor_params
      params.require(:sensor).permit(:client_ordinal_num, :channel_index, :measure_unit, :code, :unit_code, :unit_avb,
                                     :saving_type, :channel_type, :hw_port_type, :hw_port_number, :hw_port_pin_number,
                                     :calculation_type, :is_active, :calibration_table_bin, :name, :description, :channel_index)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for @sensor, html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:name].length > 0 %>">
    <%= f.label :name, t('name'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control", required: true %>
      <% if @sensor.errors[:name].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:channel_index].length > 0 %>">
    <%= f.label :channel_index, t('channel_index'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :channel_index, class: "form-control", required: true %>
      <% if @sensor.errors[:channel_index].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:measure_unit].length > 0 %>">
    <%= f.label :measure_unit, t('measure_unit'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :measure_unit, class: "form-control", required: true %>
      <% if @sensor.errors[:measure_unit].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>


  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:description].length > 0 %>">
    <%= f.label :description, t('description'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_area :description, class: "form-control", style: 'resize:vertical;', rows: 6 %>
      <% if @sensor.errors[:description].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:code].length > 0 %>">
    <%= f.label :code, t('code'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :code, class: "form-control" %>
      <% if @sensor.errors[:code].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:unit_code].length > 0 %>">
    <%= f.label :unit_code, t('unit_code'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :unit_code, class: "form-control" %>
      <% if @sensor.errors[:unit_code].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:unit_avb].length > 0 %>">
    <%= f.label :unit_avb, t('unit_avb'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :unit_avb, class: "form-control" %>
      <% if @sensor.errors[:unit_avb].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:saving_type].length > 0 %>">
    <%= f.label :saving_type, t('saving_type'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :saving_type, class: "form-control" %>
      <% if @sensor.errors[:saving_type].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:channel_type].length > 0 %>">
    <%= f.label :channel_type, t('channel_type'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :channel_type, class: "form-control" %>
      <% if @sensor.errors[:channel_type].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:hw_port_type].length > 0 %>">
    <%= f.label :hw_port_type, t('hw_port_type'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :hw_port_type, class: "form-control" %>
      <% if @sensor.errors[:hw_port_type].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:hw_port_number].length > 0 %>">
    <%= f.label :hw_port_number, t('hw_port_number'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :hw_port_number, class: "form-control" %>
      <% if @sensor.errors[:hw_port_number].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:hw_port_pin_number].length > 0 %>">
    <%= f.label :hw_port_pin_number, t('hw_port_pin_number'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :hw_port_pin_number, class: "form-control" %>
      <% if @sensor.errors[:hw_port_pin_number].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:calculation_type].length > 0 %>">
    <%= f.label :calculation_type, t('calculation_type'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :calculation_type, class: "form-control" %>
      <% if @sensor.errors[:calculation_type].length > 0 %>
      <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
      <% end %>
    </div>
  </div>

  <div class="form-group<%= ' has-error has-feedback' if @sensor.errors[:is_active].length > 0 %>">
    <div class="com-sm-4 col-sm-offset-2">
      <div class="checkbox">
        <%= f.label :is_active do %>
          <%= f.check_box(:is_active) %> <%= t('is_active') %>
        <% end %>
      </div>
    </div>
    <% if @sensor.errors[:is_active].length > 0 %>
    <span class="glyphicon glyphicon-warning-sign form-control-feedback"></span>
    <% end %>
  </div>

  <div class="actions col-sm-offset-2">
    <%= f.submit t('save'), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<%= link_to "بازگشت", sensors_path %>
<h3><%= t 'edit' %> <%= t 'sensor' %></h3>

<%= render 'form' %>

app/views/sensors/index.html.erb
<h3><%= t 'list' %> <%= t 'sensors' %></h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th class="text-center"><%= t 'tier' %></th>
      <th class="text-center"><%= t 'name' %></th>
      <th class="text-center">شماره‌ی <%= t 'sensor' %></th>
      <th class="text-center"><%= t 'description' %></th>
      <% if can? :manage, Sensor %>
        <th class="text-center"><%= t 'settings' %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% counter = 0 %>
    <% @sensors.sort_by(&:channel_index).each do |sensor| %>
      <tr class="text-center">
        <td><%= persian_numbers counter += 1 %></td>
        <td><%= link_to sensor.name, sensor %></td>
        <td><%= sensor.channel_index %></td>
        <td><%= sensor.description %></td>
        <% if can? :edit, sensor %>
          <td>
            <%= link_to t('edit'), edit_sensor_path(sensor) %>
            <%= link_to t('delete'), sensor, method: :delete, class: 'text-danger', data: { confirm: t('you_sure') } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Sensor %>
  <%= link_to icon('plus-circle', "افزودن #{t 'sensor'} جدید"), new_sensor_path, class: 'btn btn-primary' %>
<% end %>

app/views/sensors/new.html.erb
<%= link_to "بازگشت", sensors_path %>
<h3><%= t 'sensor' %> <%= t 'new' %></h3>
<% @create_action = true %>

<%= render 'form' %>

app/views/sensors/show.html.erb
<%= link_to "بازگشت", sensors_path %>
<h4>اطلاعات <%= t 'sensor' %></h4>
<dl class="dl-horizontal">
  <dt><%= t 'name' %></dt>
  <dd><%= @sensor.name %></dd><br>
  <dt><%= t 'description' %></dt>
  <dd><%= @sensor.description %></dd><br>
  <dt><%= t 'channel_index' %></dt>
  <dd><%= @sensor.channel_index %></dd><br>
  <dt><%= t 'measure_unit' %></dt>
  <dd><%= @sensor.measure_unit %></dd><br>
  <dt><%= t 'code' %></dt>
  <dd><%= @sensor.code %></dd><br>
  <dt><%= t 'unit_code' %></dt>
  <dd><%= @sensor.unit_code %></dd><br>
  <dt><%= t 'unit_avb' %></dt>
  <dd><%= @sensor.unit_avb %></dd><br>
  <dt><%= t 'saving_type' %></dt>
  <dd><%= @sensor.saving_type %></dd><br>
  <dt><%= t 'channel_type' %></dt>
  <dd><%= @sensor.channel_type %></dd><br>
  <dt><%= t 'hw_port_type' %></dt>
  <dd><%= @sensor.hw_port_type %></dd><br>
  <dt><%= t 'hw_port_number' %></dt>
  <dd><%= @sensor.hw_port_number %></dd><br>
  <dt><%= t 'hw_port_pin_number' %></dt>
  <dd><%= @sensor.hw_port_pin_number %></dd><br>
  <dt><%= t 'calculation_type' %></dt>
  <dd><%= @sensor.calculation_type %></dd><br>
  <dt><%= t 'is_active' %></dt>
  <dd><%= @sensor.is_active ? 'بلی' : 'خیر' %></dd><br>
  <% if can? :update, @sensor %>
    <%= link_to t('edit'), edit_sensor_path(@sensor), class: 'btn btn-default' %><br>
  <% end %>
</dl>