config/routes.rb
Uasco::Application.routes.draw do

  get 'me' => 'pages#me', as: 'me'
  post 'me' => 'pages#update_me'
  get 'test' => 'pages#test'
  devise_for :users
  resources :users
  resources :clients do
    collection do
      get 'compare'
    end
    member do
      get 'attachments'
      post 'attachments' => 'clients#add_attachment'
      post 'attachments/:aid' => 'clients#set_default_attachment'
      delete 'attachments/:aid' => 'clients#delete_attachment'
      get 'sensors' => 'clients#get_sensors'
      post 'sensors' => 'clients#update_sensors'
      get 'check_new'
      get 'import_usb'
      post 'import_usb' => 'clients#import_usb_post'
      get 'export'
      get 'standard_export'
      get 'import'
      post 'import' => 'clients#import_data'
      get 'live'
      get 'archive_data'
      get 'export'
      get 'export_standard'
      get 'export_shown_data'
      get 'export_live_data'
    end
  end
  resources :sensors
  resources :client_infos

  post "post_data" => "packet#recieve"

  get 'RDLSystemServer/update.php' => 'pages#get_update'

  post "/RDLSystemServer/server.php" => "packet#recieve"
  get "/RDLSystemServer/server.php" => "packet#recieve"

  post "/RDLSecondServer/server.php" => "packet#second_recieve", as: :second_server_post
  get "/RDLSecondServer/server.php" => "packet#second_recieve"

  root 'pages#app'
  get 'about' => 'pages#about'
  get 'gallery' => 'pages#gallery'
  get 'products' => 'pages#products'
  get 'contact' => 'pages#contact'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <%= link_to t('site_name'), root_path, class: 'navbar-brand' %>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-left">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        درباره‌ی شرکت <%= icon "caret-down" %>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to t('products'), products_path %>
        </li>
        <li>
          <%= link_to t('gallery'), gallery_path %>
        </li>
        <li>
          <%= link_to t('contactus'), contact_path %>
        </li>
        <li>
          <%= link_to t('aboutus'), about_path %>
        </li>
      </ul>
    </li>
    <% if current_user %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= current_user.username %> <%= icon "caret-down" %> 
        </a>
        <ul class="dropdown-menu dropdown-user">
          <li>
            <%= link_to icon(:user, t('user_profile')), me_path %>
          </li>
          <li>
            <%= link_to icon("sign-out", t('logout')), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to t('login'), new_user_session_path %>
      </li>
    <% end %>
  </ul>
  <!-- /.navbar-top-links -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="side-menu">
      <li <%= 'class=active' unless @tab %>>
        <%= link_to raw(icon :dashboard, 'صفحه اصلی'), root_path %>
      </li>
      <% if can? :read, Client %>
        <li <%= 'class=active' if @tab == 'client' %>>
          <%= link_to icon("bar-chart-o", raw("#{t('clients')}")), clients_path %>
        </li>
      <% end %>
      <% if can? :read, ClientInfo %>
        <li <%= 'class=active' if @tab == 'client_info' %>>
          <%= link_to icon("hdd-o", raw("#{t('client_infos')}")), client_infos_path %>
        </li>
      <% end %>
      <% if can? :edit, Sensor %>
        <li <%= 'class=active' if @tab == 'sensor' %>>
          <%= link_to icon("briefcase", raw("#{t('sensors')}")), sensors_path %>
        </li>
      <% end %>
      <% if can? :read, User %>
        <li <%= 'class=active' if @tab == 'user' %>>
          <%= link_to icon("users", raw("#{t('users')}")), users_path %>
        </li>
      <% end %>
      <li <%= 'class=active' if @tab == 'compare' %>>
        <%= link_to icon("copy", raw("#{t('compare')}")), compare_clients_path %>
      </li>
      <!-- <li>
        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
      </li>
      <li>
        <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse">
          <li>
            <a href="panels-wells.html">Panels and Wells</a>
          </li>
          <li>
            <a href="buttons.html">Buttons</a>
          </li>
          <li>
            <a href="notifications.html">Notifications</a>
          </li>
          <li>
            <a href="typography.html">Typography</a>
          </li>
          <li>
            <a href="grid.html">Grid</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse">
          <li>
            <a href="#">Second Level Item</a>
          </li>
          <li>
            <a href="#">Second Level Item</a>
          </li>
          <li>
            <a href="#">Third Level <span class="fa arrow"></span></a>
            <ul class="nav nav-third-level collapse">
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <li>
        <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse">
          <li>
            <a href="blank.html">Blank Page</a>
          </li>
          <li>
            <a href="login.html">Login Page</a>
          </li>
        </ul>
      </li> -->
    </ul>
    <!-- /#side-menu -->
  </div>
  <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9"> 
  <title><%= content_for?(:title) ? yield(:title) : t('site_title') %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="/assets/html5shiv.js"></script>
    <script src="/assets/respond.min.js"></script>
    <script src="/assets/excanvas.js"></script>
  <![endif]-->
</head>
<body>

<%= render 'layouts/header' %>
<% if @app %>
  <% if signed_in? %>
    <%= render 'layouts/sidebar' %>
    <div id="page-wrapper" class="clearfix">
      <div class="col-sm-12">
        <% if flash.count %>
          <% flash.each do |key, msg| %>
            <div class="<%= flash_class(key) %> alert-dismissable" style="margin-top: 20px;">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= msg %>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  <% else %>
    <div class="container login-page">
      <% if flash.count %>
        <% flash.each do |key, msg| %>
          <div class="<%= flash_class(key) %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= msg %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  <% end %>
<% else %>
  <div id="main-page">
    <div class="container">
      <%= yield %>
    </div>
  </div>
<% end %>

<%= javascript_include_tag "application" %>
</body>
</html>